### ISSUE TITLE
Error in src/App.jsx

### ISSUE THREAD

**Issue by janvinsha** [ethereum-boilerplate/ethereum-nft-marketplace-boilerplate#16]
Error in src/App.jsx, "styles" is not defined on line 37, 62 and 68
The error makes the app to show a blank screen

**Comment by 0xPr0f** [comment]
Hello, this styles here (https://github.com/ethereum-boilerplate/ethereum-nft-marketplace-boilerplate/blob/449d31c9bbc4cd55b90c4a16d080a50153c4ba7c/src/App.jsx#L23) has to be the same spelling and has to be there if you are using component from that variable

**Comment by YosephKS** [comment]
> Error in src/App.jsx, "styles" is not defined on line 37, 62 and 68 The error makes the app to show a blank screen

for this one somehow can't replicate the issue at all, since in `App.jsx` there is the `styles` as @0xPr0f shown there 🤔
