### ISSUE TITLE
Event configuration details

### ISSUE THREAD

**Issue by Agnostic** [ethereum-boilerplate/ethereum-nft-marketplace-boilerplate#2]
Hi, could you please provide more details for the event configuration?

The moralis configuration accepts a JSON object, it is also asking for a "topic" and a listening address.

![image](https://user-images.githubusercontent.com/1162988/147602903-c258ffd4-ca85-4667-98e7-15f31ef26a7d.png)

**Comment by ivan-liljeqvist** [comment]
Check this https://youtu.be/LMqqxkuo7b0

for more questions please ask in https://forum.moralis.io
