### ISSUE TITLE
i try to add nft price it work fine for 999 value but it not work with 1000 and greater

### ISSUE THREAD

**Issue by pkgujjar** [ethereum-boilerplate/ethereum-nft-marketplace-boilerplate#4]
i try to add nft price it work fine for 999 value but it not work with 1000 and greater
sreenshot here https://paste.pics/47bf36f39894e475dcf18c10de9bf7c9
i try post on https://forum.moralis.io/t/cloning-opensea-nft-boilerplate-questions/5107/2
but it not posted and give error of this 
"We're sorry, but new users are temporarily limited to 3 replies in the same topic."

my forum.moralis id https://forum.moralis.io/u/pkgujjar/

**Comment by ivan-liljeqvist** [comment]
I changed your trust level in the forum - please continue there
